name: Lint

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  checks: write
  contents: write

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2

      - name: Set up Node.js
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3
        with:
          node-version: 16

      - name: Install project dependencies
        run: yarn --prefer-offline
        id: install

      - name: yarn lint
